services:
  nginx:
    image: nginx:latest
    volumes:
      - ../app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    depends_on:
      - app
    ports:
      - "8088:80"

  app:
    build:
      context: ./app
    volumes:
      - ../app:/var/www
      - ./app/php.ini:/usr/local/etc/php/conf.d/php.ini
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    container_name: ${PROJECT_NAME}-app
    restart: always

  redis:
    image: redis:latest
    container_name: ${PROJECT_NAME}-redis
    restart: always
#    ports:
#      - "63798:6379"
    volumes:
      - ./redis-data:/data
